import DeviceElement from "./device-element";
import DeviceControl from "./device-control";
declare class DeviceWidget extends DeviceControl {
    readonly tag: string;
    classNames: string[];
    children: any[] | undefined;
    innerText: string | undefined;
    innerHTML: string | undefined;
    overflowY: "auto" | "scroll" | undefined;
    overflowX: "auto" | "scroll" | undefined;
    scrollBarsHolderDeviceElement: ScrollBarsHolderDeviceElement | undefined;
    scrollableContentDeviceElement: DeviceElement | undefined;
    constructor(tag: string, ...params: any);
    getTag(): string;
    getClassName(): string;
    hasClassName(className: string): boolean;
    addClassName(className: string): this;
    removeClassName(className: string): this;
    toggleClassName(className: string): this;
    resetClassName(): this;
    setProp(propName: string, propValue: string): this;
    getStyle(): any;
    setStyle(style: any): this;
    getStyleRule(ruleName: string): any;
    setStyleRule(ruleName: string, ruleValue: string): this;
    setOverflowY(overflowY: "auto" | "scroll"): this;
    setOverflowX(overflowX: "auto" | "scroll"): this;
    setOverflow(overflow: "auto" | "scroll"): this;
    getInnerText(): string | undefined;
    setInnerText(innerText: string | undefined): this;
    getInnerHTML(): string | undefined;
    setInnerHTML(innerHTML: string | undefined): this;
    getChildren(): any[];
    add(child: any): any;
    removeAll(): void;
    createDeviceElement(): DeviceElement;
    createInnerDeviceElements(parentDeviceElement: DeviceElement): void;
    createHTMLString(): any;
    callDidMount(): void;
    createScrollBars(): void;
    getBoundingClientRect(): DOMRect | undefined;
    setFocus(): void;
}
declare class ScrollBarsHolderDeviceElement extends DeviceElement {
    deviceWidget: DeviceWidget;
    overflowY: "auto" | "scroll" | undefined;
    overflowX: "auto" | "scroll" | undefined;
    htmlVerticalScrollBar: HTMLElement | undefined;
    htmlHorizontalScrollBar: HTMLElement | undefined;
    constructor(deviceWidget: DeviceWidget, overflowY: "auto" | "scroll" | undefined, overflowX: "auto" | "scroll" | undefined);
}
export default DeviceWidget;
